services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    command: npm run dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
    environment:
      - TOKEN: crkEbzhJpJa2LqUi4CxQrGZMHr542LBVsYOlvu7H
      - DB_HOST: postgres
      - DB_PORT: 5432
      - DB_USER: postgres
      - DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      - DB_NAME: postgres
      - SEED_HOST: localhost
      - SEED_ADMIN_MAIL: admin@mail.fr
      - SEED_ADMIN_PASSWORD: Admin@3010
      - FRONTEND_URL: http://localhost:3000
      - DEPLOY_URL: https://city-guide.aimach.fr
      - BACK_PORT: 5000

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_PUBLIC_BACKEND_URL=http://localhost:5000

  postgres:
    image: "postgis/postgis"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
