services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    env_file:
      - .env.local
    ports:
      - 5000:5000
    healthcheck:
      test: 'curl --fail --request GET --url "http://localhost:5000/api/cities" || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  testrunner:
    build: ./testrunner
    depends_on:
      backend:
        condition: service_healthy
