services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    command: npm run dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

  postgres:
    image: "postgis/postgis"
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
