services:
   backend:
      build: ./backend
      ports:
         - 5000:5000
      command: npm run dev
      volumes:
         - ./backend/src:/app/src
         - ./backend/public:/app/public
      env_file:
         - ./backend/.env

   frontend:
      build: ./frontend
      ports:
         - 3000:3000
      volumes:
         - ./frontend/src:/app/src
      environment:
         - WDS_SOCKET_HOST=127.0.0.1
         - CHOKIDAR_USEPOLLING=true
         - WATCHPACK_POLLING=true

  postgres:
    image: "postgis/postgis"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

   adminer:
      image: adminer
      restart: always
      ports:
         - 8080:8080
